apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: cyplay
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: test-automation-operator@idfy-kyc-staging.iam.gserviceaccount.com
          maxRetries: 0
          containers:
            - name: cyplay
              resources:
                limits:
                  memory: 1Gi
              image: asia-south1-docker.pkg.dev/idfy-gitlab/idfy/cyplay:2be3fab18235c4190353747bd76afe4567754b76
              args:
                - -scypress/e2e/tasky_cypress_with_playwright/tasky001_tasky_sanity.cy.js
              env:
                - name: cypress_channel
                  value: chrome
                - name: cypress_environment
                  value: staging
                - name: cypress_client
                  value: e1dc
                - name: cypress_username
                  value: cloud
                - name: cypress_gchat_reports
                  value: "false"
                - name: cypress_email_reports
                  value: "false"
                - name: cypress_creds
                  value: '{"login001":{"email":"vs.automation@idfy.com","password":"Password@123"}}'
                - name: cypress_youtrack
                  value: ""
                - name: cypress_adhoc_email_group
                  value: ""
